version: '3.3'
services:
   jenkins:
     build: ./jenkins
     ports:
      - "8080:8080"

   webserver:
     build: ./webserver
     ports:
      - "80:80"

   tomcat7:
     build: ./tomcat7
     ports:
      - "8081:8080"
